services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - target=dev
    volumes:
      - .:/app
    ports:
      - 8080:8080

  db:
    image: mysql:8.4.5
    ports:
      - ${DB_PORT}:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    platform: linux/amd64

volumes:
  mysql-data:
    driver: local
