[tools]
go = "1.26.0"
atlas = "1.1.0"
pnpm = "10.24.0"
"npm:commitlint" = "19.8.1"
"npm:lefthook" = "1.11.14"
"npm:prettier" = "3.5.3"
"npm:openapi-generate-html" = "0.5.3"
"npm:serve" = "14.2.6"

[hooks]
postinstall = "lefthook install"

[tasks.install-tools]
description = "Install all tools"
run = [
  "go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.10.1",
  "go install golang.org/x/tools/gopls@v0.21.1",
  "go install github.com/go-delve/delve/cmd/dlv@v1.26.0",
  "go install github.com/air-verse/air@v1.64.5",
  "go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@v2.6.0",
]

[tasks.db-exec]
description = "Open a MySQL shell in the database container"
run = ["docker compose exec db mysql -uroot -prootpassword example"]

[tasks.gorm-gen]
description = "Generate GORM models"
run = ["go run scripts/gorm_gen/main.go"]

[tasks.atlas-inspect]
description = "Inspect the database schema and generate the atlas file"
run = ["atlas schema inspect --env local"]

[tasks.atlas-apply]
description = "Run database migrations"
run = ["atlas schema apply --env local"]

[tasks.swagger]
description = "Build and serve Swagger documentation"
run = ["mise run swagger-build", "mise run swagger-serve"]

[tasks.swagger-build]
description = "Build Swagger documentation"
run = [
  "openapi-generate-html -i openapi/schema/openapi.yaml --theme light --ui stoplight -o openapi/html/index.html",
]

[tasks.swagger-serve]
description = "Serve Swagger documentation"
run = ["serve -l 6608 openapi/html"]

[tasks.typespec-install]
description = "Install TypeSpec dependencies"
run = ["pnpm install -C ./typespec"]

[tasks.typespec-compile]
description = "Compile TypeSpec files"
run = ["pnpm -C ./typespec typespec"]

[tasks.oapi-gen-gin]
description = "Generate Go code from OpenAPI specification"
run = [
  "oapi-codegen -generate gin -package gen ./openapi/schema/openapi.yaml > internal/handler/gen/gin.gen.go",
]

[tasks.oapi-gen-types]
description = "Generate Go code from OpenAPI specification"
run = [
  "oapi-codegen -generate types -package gen openapi/schema/openapi.yaml > internal/handler/gen/types.gen.go",
]

[tasks.oapi-gen-spec]
description = "Generate Go code from OpenAPI specification"
run = [
  "oapi-codegen -generate spec -package gen openapi/schema/openapi.yaml > internal/handler/gen/spec.gen.go",
]

[tasks.oapi-gen-client]
description = "Generate Go code from OpenAPI specification"
run = [
  "oapi-codegen -generate client -package gen openapi/schema/openapi.yaml > internal/handler/gen/client.gen.go",
]

[tasks.oapi-gen]
description = "Generate Go code from OpenAPI specification"
run = ["mise run oapi-gen-gin", "mise run oapi-gen-types"]

[env]
DB_HOST = "localhost"
DB_PORT = "3306"
DB_USER = "root"
DB_PASSWORD = "rootpassword"
DB_NAME = "example"
