// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/tf63/go-template/internal/interface/mysql_gen/model"
)

func newCat(db *gorm.DB, opts ...gen.DOOption) cat {
	_cat := cat{}

	_cat.catDo.UseDB(db, opts...)
	_cat.catDo.UseModel(&model.Cat{})

	tableName := _cat.catDo.TableName()
	_cat.ALL = field.NewAsterisk(tableName)
	_cat.ID = field.NewInt32(tableName, "id")
	_cat.Name = field.NewString(tableName, "name")
	_cat.Age = field.NewInt32(tableName, "age")

	_cat.fillFieldMap()

	return _cat
}

type cat struct {
	catDo catDo

	ALL  field.Asterisk
	ID   field.Int32
	Name field.String
	Age  field.Int32

	fieldMap map[string]field.Expr
}

func (c cat) Table(newTableName string) *cat {
	c.catDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cat) As(alias string) *cat {
	c.catDo.DO = *(c.catDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cat) updateTableName(table string) *cat {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt32(table, "id")
	c.Name = field.NewString(table, "name")
	c.Age = field.NewInt32(table, "age")

	c.fillFieldMap()

	return c
}

func (c *cat) WithContext(ctx context.Context) ICatDo { return c.catDo.WithContext(ctx) }

func (c cat) TableName() string { return c.catDo.TableName() }

func (c cat) Alias() string { return c.catDo.Alias() }

func (c cat) Columns(cols ...field.Expr) gen.Columns { return c.catDo.Columns(cols...) }

func (c *cat) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cat) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 3)
	c.fieldMap["id"] = c.ID
	c.fieldMap["name"] = c.Name
	c.fieldMap["age"] = c.Age
}

func (c cat) clone(db *gorm.DB) cat {
	c.catDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cat) replaceDB(db *gorm.DB) cat {
	c.catDo.ReplaceDB(db)
	return c
}

type catDo struct{ gen.DO }

type ICatDo interface {
	gen.SubQuery
	Debug() ICatDo
	WithContext(ctx context.Context) ICatDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICatDo
	WriteDB() ICatDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICatDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICatDo
	Not(conds ...gen.Condition) ICatDo
	Or(conds ...gen.Condition) ICatDo
	Select(conds ...field.Expr) ICatDo
	Where(conds ...gen.Condition) ICatDo
	Order(conds ...field.Expr) ICatDo
	Distinct(cols ...field.Expr) ICatDo
	Omit(cols ...field.Expr) ICatDo
	Join(table schema.Tabler, on ...field.Expr) ICatDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICatDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICatDo
	Group(cols ...field.Expr) ICatDo
	Having(conds ...gen.Condition) ICatDo
	Limit(limit int) ICatDo
	Offset(offset int) ICatDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICatDo
	Unscoped() ICatDo
	Create(values ...*model.Cat) error
	CreateInBatches(values []*model.Cat, batchSize int) error
	Save(values ...*model.Cat) error
	First() (*model.Cat, error)
	Take() (*model.Cat, error)
	Last() (*model.Cat, error)
	Find() ([]*model.Cat, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Cat, err error)
	FindInBatches(result *[]*model.Cat, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Cat) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICatDo
	Assign(attrs ...field.AssignExpr) ICatDo
	Joins(fields ...field.RelationField) ICatDo
	Preload(fields ...field.RelationField) ICatDo
	FirstOrInit() (*model.Cat, error)
	FirstOrCreate() (*model.Cat, error)
	FindByPage(offset int, limit int) (result []*model.Cat, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICatDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c catDo) Debug() ICatDo {
	return c.withDO(c.DO.Debug())
}

func (c catDo) WithContext(ctx context.Context) ICatDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c catDo) ReadDB() ICatDo {
	return c.Clauses(dbresolver.Read)
}

func (c catDo) WriteDB() ICatDo {
	return c.Clauses(dbresolver.Write)
}

func (c catDo) Session(config *gorm.Session) ICatDo {
	return c.withDO(c.DO.Session(config))
}

func (c catDo) Clauses(conds ...clause.Expression) ICatDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c catDo) Returning(value interface{}, columns ...string) ICatDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c catDo) Not(conds ...gen.Condition) ICatDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c catDo) Or(conds ...gen.Condition) ICatDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c catDo) Select(conds ...field.Expr) ICatDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c catDo) Where(conds ...gen.Condition) ICatDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c catDo) Order(conds ...field.Expr) ICatDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c catDo) Distinct(cols ...field.Expr) ICatDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c catDo) Omit(cols ...field.Expr) ICatDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c catDo) Join(table schema.Tabler, on ...field.Expr) ICatDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c catDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICatDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c catDo) RightJoin(table schema.Tabler, on ...field.Expr) ICatDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c catDo) Group(cols ...field.Expr) ICatDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c catDo) Having(conds ...gen.Condition) ICatDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c catDo) Limit(limit int) ICatDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c catDo) Offset(offset int) ICatDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c catDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICatDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c catDo) Unscoped() ICatDo {
	return c.withDO(c.DO.Unscoped())
}

func (c catDo) Create(values ...*model.Cat) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c catDo) CreateInBatches(values []*model.Cat, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c catDo) Save(values ...*model.Cat) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c catDo) First() (*model.Cat, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Cat), nil
	}
}

func (c catDo) Take() (*model.Cat, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Cat), nil
	}
}

func (c catDo) Last() (*model.Cat, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Cat), nil
	}
}

func (c catDo) Find() ([]*model.Cat, error) {
	result, err := c.DO.Find()
	return result.([]*model.Cat), err
}

func (c catDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Cat, err error) {
	buf := make([]*model.Cat, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c catDo) FindInBatches(result *[]*model.Cat, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c catDo) Attrs(attrs ...field.AssignExpr) ICatDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c catDo) Assign(attrs ...field.AssignExpr) ICatDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c catDo) Joins(fields ...field.RelationField) ICatDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c catDo) Preload(fields ...field.RelationField) ICatDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c catDo) FirstOrInit() (*model.Cat, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Cat), nil
	}
}

func (c catDo) FirstOrCreate() (*model.Cat, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Cat), nil
	}
}

func (c catDo) FindByPage(offset int, limit int) (result []*model.Cat, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c catDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c catDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c catDo) Delete(models ...*model.Cat) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *catDo) withDO(do gen.Dao) *catDo {
	c.DO = *do.(*gen.DO)
	return c
}
