// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/tf63/go-template/internal/interface/mysql_gen/model"
)

func newDog(db *gorm.DB, opts ...gen.DOOption) dog {
	_dog := dog{}

	_dog.dogDo.UseDB(db, opts...)
	_dog.dogDo.UseModel(&model.Dog{})

	tableName := _dog.dogDo.TableName()
	_dog.ALL = field.NewAsterisk(tableName)
	_dog.ID = field.NewInt32(tableName, "id")
	_dog.Name = field.NewString(tableName, "name")
	_dog.Age = field.NewInt32(tableName, "age")

	_dog.fillFieldMap()

	return _dog
}

type dog struct {
	dogDo dogDo

	ALL  field.Asterisk
	ID   field.Int32
	Name field.String
	Age  field.Int32

	fieldMap map[string]field.Expr
}

func (d dog) Table(newTableName string) *dog {
	d.dogDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d dog) As(alias string) *dog {
	d.dogDo.DO = *(d.dogDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *dog) updateTableName(table string) *dog {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt32(table, "id")
	d.Name = field.NewString(table, "name")
	d.Age = field.NewInt32(table, "age")

	d.fillFieldMap()

	return d
}

func (d *dog) WithContext(ctx context.Context) IDogDo { return d.dogDo.WithContext(ctx) }

func (d dog) TableName() string { return d.dogDo.TableName() }

func (d dog) Alias() string { return d.dogDo.Alias() }

func (d dog) Columns(cols ...field.Expr) gen.Columns { return d.dogDo.Columns(cols...) }

func (d *dog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *dog) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 3)
	d.fieldMap["id"] = d.ID
	d.fieldMap["name"] = d.Name
	d.fieldMap["age"] = d.Age
}

func (d dog) clone(db *gorm.DB) dog {
	d.dogDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d dog) replaceDB(db *gorm.DB) dog {
	d.dogDo.ReplaceDB(db)
	return d
}

type dogDo struct{ gen.DO }

type IDogDo interface {
	gen.SubQuery
	Debug() IDogDo
	WithContext(ctx context.Context) IDogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDogDo
	WriteDB() IDogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDogDo
	Not(conds ...gen.Condition) IDogDo
	Or(conds ...gen.Condition) IDogDo
	Select(conds ...field.Expr) IDogDo
	Where(conds ...gen.Condition) IDogDo
	Order(conds ...field.Expr) IDogDo
	Distinct(cols ...field.Expr) IDogDo
	Omit(cols ...field.Expr) IDogDo
	Join(table schema.Tabler, on ...field.Expr) IDogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDogDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDogDo
	Group(cols ...field.Expr) IDogDo
	Having(conds ...gen.Condition) IDogDo
	Limit(limit int) IDogDo
	Offset(offset int) IDogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDogDo
	Unscoped() IDogDo
	Create(values ...*model.Dog) error
	CreateInBatches(values []*model.Dog, batchSize int) error
	Save(values ...*model.Dog) error
	First() (*model.Dog, error)
	Take() (*model.Dog, error)
	Last() (*model.Dog, error)
	Find() ([]*model.Dog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Dog, err error)
	FindInBatches(result *[]*model.Dog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Dog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDogDo
	Assign(attrs ...field.AssignExpr) IDogDo
	Joins(fields ...field.RelationField) IDogDo
	Preload(fields ...field.RelationField) IDogDo
	FirstOrInit() (*model.Dog, error)
	FirstOrCreate() (*model.Dog, error)
	FindByPage(offset int, limit int) (result []*model.Dog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d dogDo) Debug() IDogDo {
	return d.withDO(d.DO.Debug())
}

func (d dogDo) WithContext(ctx context.Context) IDogDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d dogDo) ReadDB() IDogDo {
	return d.Clauses(dbresolver.Read)
}

func (d dogDo) WriteDB() IDogDo {
	return d.Clauses(dbresolver.Write)
}

func (d dogDo) Session(config *gorm.Session) IDogDo {
	return d.withDO(d.DO.Session(config))
}

func (d dogDo) Clauses(conds ...clause.Expression) IDogDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d dogDo) Returning(value interface{}, columns ...string) IDogDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d dogDo) Not(conds ...gen.Condition) IDogDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d dogDo) Or(conds ...gen.Condition) IDogDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d dogDo) Select(conds ...field.Expr) IDogDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d dogDo) Where(conds ...gen.Condition) IDogDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d dogDo) Order(conds ...field.Expr) IDogDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d dogDo) Distinct(cols ...field.Expr) IDogDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d dogDo) Omit(cols ...field.Expr) IDogDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d dogDo) Join(table schema.Tabler, on ...field.Expr) IDogDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d dogDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDogDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d dogDo) RightJoin(table schema.Tabler, on ...field.Expr) IDogDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d dogDo) Group(cols ...field.Expr) IDogDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d dogDo) Having(conds ...gen.Condition) IDogDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d dogDo) Limit(limit int) IDogDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d dogDo) Offset(offset int) IDogDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d dogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDogDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d dogDo) Unscoped() IDogDo {
	return d.withDO(d.DO.Unscoped())
}

func (d dogDo) Create(values ...*model.Dog) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d dogDo) CreateInBatches(values []*model.Dog, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d dogDo) Save(values ...*model.Dog) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d dogDo) First() (*model.Dog, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Dog), nil
	}
}

func (d dogDo) Take() (*model.Dog, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Dog), nil
	}
}

func (d dogDo) Last() (*model.Dog, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Dog), nil
	}
}

func (d dogDo) Find() ([]*model.Dog, error) {
	result, err := d.DO.Find()
	return result.([]*model.Dog), err
}

func (d dogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Dog, err error) {
	buf := make([]*model.Dog, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d dogDo) FindInBatches(result *[]*model.Dog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d dogDo) Attrs(attrs ...field.AssignExpr) IDogDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d dogDo) Assign(attrs ...field.AssignExpr) IDogDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d dogDo) Joins(fields ...field.RelationField) IDogDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d dogDo) Preload(fields ...field.RelationField) IDogDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d dogDo) FirstOrInit() (*model.Dog, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Dog), nil
	}
}

func (d dogDo) FirstOrCreate() (*model.Dog, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Dog), nil
	}
}

func (d dogDo) FindByPage(offset int, limit int) (result []*model.Dog, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d dogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d dogDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d dogDo) Delete(models ...*model.Dog) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *dogDo) withDO(do gen.Dao) *dogDo {
	d.DO = *do.(*gen.DO)
	return d
}
