// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCat = "cats"

// Cat mapped from table <cats>
type Cat struct {
	ID   int32  `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Name string `gorm:"column:name;type:varchar(255);not null" json:"name"`
	Age  int32  `gorm:"column:age;type:int;not null" json:"age"`
}

// TableName Cat's table name
func (*Cat) TableName() string {
	return TableNameCat
}
