// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDog = "dogs"

// Dog mapped from table <dogs>
type Dog struct {
	ID   int32  `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Name string `gorm:"column:name;type:varchar(255);not null" json:"name"`
	Age  int32  `gorm:"column:age;type:int;not null" json:"age"`
}

// TableName Dog's table name
func (*Dog) TableName() string {
	return TableNameDog
}
